"""Remove volatility

Revision ID: e9b5f8adf047
Revises: 94b640653b2d
Create Date: 2021-08-17 14:39:45.396277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b5f8adf047'
down_revision = '94b640653b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('volatility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column('volatility')
    # ### end Alembic commands ###
